# Generated by Django 5.2 on 2025-04-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_faculty_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
